version: 2.1

jobs:
  run-unit-tests:
    macos:
      xcode: 13.4.1
    environment:
      FASTLANE_LANE: run_unit_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout 
      - run:
          name: "run unit tests"
          command: "xcodebuild test -scheme RedditUnitTests -destination 'platform=iOS Simulator,id=0173AE56-BA34-4C95-9BC0-801F1F8CCAC7'"
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/unit_tests

  run-ui-tests:
    macos:
      xcode: 13.4.1
    environment: 
      FASTLANE_LANE: run_ui_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout 
      - run:
          name: "run ui tests"
          command: "xcodebuild test -scheme RedditUITests -destination 'platform=iOS Simulator,id=0173AE56-BA34-4C95-9BC0-801F1F8CCAC7'"
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/ui_tests
workflows:
  build-and-run-tests:
    jobs:
      - run-unit-tests
      - run-ui-tests:
          requires:
            - run-unit-tests