version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

executors:
  mac-executor:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project

jobs:
  run-unit-tests:
    executor:
      name: mac-executor
    environment:
      FASTLANE_LANE: run_unit_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout 
      - ruby/install-deps
      - run: 
          name: Run unit tests
          command: |
            mkdir -p ~/unit_tests_results 
            xcodebuild test -scheme RedditUnitTests -destination 'platform=iOS Simulator,id=0173AE56-BA34-4C95-9BC0-801F1F8CCAC7'
      - store_test_results:
          path: ~/unit_tests_results

  run-ui-tests:
    executor:
      name: mac-executor  
    environment: 
      FASTLANE_LANE: run_ui_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout 
      - ruby/install-deps
      - run: mkdir -p output/ui_tests_results
      - run: bundle exec fastlane $FASTLANE_LANE
      - store_test_results:
          path: output/ui_tests_results
      - store_artifacts:
          path: output
workflows:
  build-and-run-tests:
    jobs:
      - run-unit-tests
      # - run-ui-tests:
      #     requires:
      #       - run-unit-tests