version: 2.1

jobs:
  run-unit-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout 
      - run:
          name: "run unit tests"
          command: "xcodebuild test -scheme RedditUnitTests -destination 'platform=iOS Simulator,id=0173AE56-BA34-4C95-9BC0-801F1F8CCAC7'"
  run-ui-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout 
      - run:
          name: "run ui tests"
          command: "xcodebuild test -scheme RedditUITests -destination 'platform=iOS Simulator,id=0173AE56-BA34-4C95-9BC0-801F1F8CCAC7'"
workflows:
  build-and-run-tests:
    jobs:
      - run-unit-tests
      - run-ui-tests