version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  run-unit-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout 
      - ruby/install-deps
      - run:
          name: "run unit tests"
          command: "bundle exec fastlane pwd"
          # command: "bundle exec fastlane run_unit_tests"
  run-ui-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout 
      - ruby/install-deps
      - run:
          name: "run ui tests"
          command: "bundle exec fastlane run_ui_tests"
workflows:
  build-and-run-tests:
    jobs:
      - run-unit-tests
      - run-ui-tests:
          requires:
            - run-unit-tests